### PR TITLE
Add the requesting user from the Authentication object to the request

### PR DESCRIPTION
**Pull request by kmschoep-usgs**
parameters for the lambda report.

### CODE REVIEW

**Review by zmoore-usgs — COMMENTED** [review]
This is intended to be passing the requesting user down to the lambda function building the report, right?

Or was this intending to provide the logged-in username back to the UI?

**Comment by kmschoep-usgs** [comment]
This is intended to be passing the requesting user down to the lambda function building the report, which then is added to the ReportMetadata, which has the effect of providing the logged-in username to the UI.

**Comment by zmoore-usgs** [comment]
Gotcha, okay. I think passing the requesting user down to the Lambda makes sense! I'm wondering if we also need a direct API to grab the logged-in user from the Gateway? For example - 

- If someone navigates to the UI and updates a folder before running a report we wouldn't have the username of the user modifying the folder. We could just grab the username of the user who updates a folder from the service when they run that request, rather than having that username as a parameter of the request passed from the UI, instead though.

- Another possibility - If we want to add any info on the logged-in user to the header (like "You are logged in as _______" or something)  we'd need to wait for the user to run a report first before we'd have their username. Bug also not sure that's a valid use-case.

Not sure if either of those situations are valid or not, but figured I'd ask. Otherwise changes look good!

**Comment by kmschoep-usgs** [comment]
Yes, we still need those use cases fulfilled, and I think AQCU-2036 is intended to do that.

**Comment by SMH94** [comment]
Nice! Learning some good stuff here

**Comment by zmoore-usgs** [comment]
Ahh I gotcha, I was thinking that 2036 was the one you took over. Okay this makes sense then, thanks! 👍

**Review by zmoore-usgs — APPROVED** [review]

**Review by SMH94 — APPROVED** [review]

**Pull request merged**
